### ISSUE TITLE
Troubles to compile from source with node 8

### ISSUE THREAD

**Issue by kud** [mozilla/mozjpeg#261]
```
> mozjpeg@4.1.1 postinstall /Users/kud/Projects/_contexte/lois-webapp/node_modules/mozjpeg
> node lib/install.js

  ⚠ Response code 404 (Not Found)
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/Users/kud/Projects/_contexte/lois-webapp/node_modules/mozjpeg/vendor" --bindir="/Users/kud/Projects/_contexte/lois-webapp/node_modules/mozjpeg/vendor" --libdir="/Users/kud/Projects/_contexte/lois-webapp/node_modules/mozjpeg/vendor" && make --jobs=4 && make install --jobs=4
Command failed: ./configure --disable-shared --prefix="/Users/kud/Projects/_contexte/lois-webapp/node_modules/mozjpeg/vendor" --bindir="/Users/kud/Projects/_contexte/lois-webapp/node_modules/mozjpeg/vendor" --libdir="/Users/kud/Projects/_contexte/lois-webapp/node_modules/mozjpeg/vendor"
configure: error: installation or configuration problem: assembler cannot create object files.

    at ChildProcess.exithandler (child_process.js:252:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
```

(trying to install it via `image-webpack-loader`)

**Comment by kud** [comment]
(Works with other libs)

```
> pngquant-bin@3.1.1 postinstall /Users/kud/Projects/_contexte/lois-webapp/node_modules/pngquant-bin
> node lib/install.js

  ⚠ Response code 404 (Not Found)
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant built successfully

> optipng-bin@3.1.4 postinstall /Users/kud/Projects/_contexte/lois-webapp/node_modules/optipng-bin
> node lib/install.js

  ⚠ Response code 404 (Not Found)
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✔ optipng built successfully
```

**Comment by kud** [comment]
(maybe useful)

```
> fsevents@1.1.1 install /Users/kud/Projects/_contexte/lois-webapp/node_modules/fsevents
> node install

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/Cellar/node/8.0.0_1/bin/node',
node-pre-gyp verb cli   '/Users/kud/Projects/_contexte/lois-webapp/node_modules/fsevents/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@https://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.6.33.tgz
node-pre-gyp info using node@8.0.0 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack TypeError: Cannot read property 'version' of null
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/kud/Projects/_contexte/lois-webapp/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:270:32)
node-pre-gyp ERR! stack     at install (/Users/kud/Projects/_contexte/lois-webapp/node_modules/fsevents/node_modules/node-pre-gyp/lib/install.js:168:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/kud/Projects/_contexte/lois-webapp/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:50:37)
node-pre-gyp ERR! stack     at run (/Users/kud/Projects/_contexte/lois-webapp/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/kud/Projects/_contexte/lois-webapp/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:569:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:580:10)
node-pre-gyp ERR! stack     at Module.load (module.js:503:32)
node-pre-gyp ERR! stack     at tryModuleLoad (module.js:466:12)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:458:3)
node-pre-gyp ERR! System Darwin 16.6.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/8.0.0_1/bin/node" "/Users/kud/Projects/_contexte/lois-webapp/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/kud/Projects/_contexte/lois-webapp/node_modules/fsevents
node-pre-gyp ERR! node -v v8.0.0
node-pre-gyp ERR! node-pre-gyp -v vhttps://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.6.33.tgz
node-pre-gyp ERR! not ok
Cannot read property 'version' of null
```

**Comment by pornel** [comment]
This project is not related to Node.js. Please ask maintainers of Node packages for help.

**Comment by kud** [comment]
I can understand @pornel but

```
autoreconf -fiv && ./configure --disable-shared --prefix="/Users/kud/Projects/_contexte/lois-webapp/node_modules/mozjpeg/vendor" --bindir="/Users/kud/Projects/_contexte/lois-webapp/node_modules/mozjpeg/vendor" --libdir="/Users/kud/Projects/_contexte/lois-webapp/node_modules/mozjpeg/vendor" && make --jobs=4 && make install --jobs=4
Command failed: ./configure --disable-shared --prefix="/Users/kud/Projects/_contexte/lois-webapp/node_modules/mozjpeg/vendor" --bindir="/Users/kud/Projects/_contexte/lois-webapp/node_modules/mozjpeg/vendor" --libdir="/Users/kud/Projects/_contexte/lois-webapp/node_modules/mozjpeg/vendor"
configure: error: installation or configuration problem: assembler cannot create object files.
```

isn't a node command, no?

**Comment by njdoyle** [comment]
Looks like the relevant Node people incorrectly assume you have nasa installed I would guess.

**Comment by kud** [comment]
Okay @njdoyle , thank you, i'll investigate. :)
