### ISSUE TITLE
Ubuntu 18.04.3 mozjpeg pre-build test failed

### ISSUE THREAD

**Issue by RicoLiu** [mozilla/mozjpeg#357]
npm install error log:

```
⚠ connect ETIMEDOUT 151.101.108.133:443
⚠ mozjpeg pre-build test failed
ℹ compiling from source
✖ RequestError: getaddrinfo EAI_AGAIN github-production-release-asset-2e65be.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com:443
    at ClientRequest.req.once.err (/home/jenkins/workspace/upload_html5_industry_all/HTML5/industry/healthRecord/node_modules/got/index.js:111:21)
    at Object.onceWrapper (events.js:281:20)
    at ClientRequest.emit (events.js:193:13)
    at TLSSocket.socketErrorListener (_http_client.js:397:9)
    at TLSSocket.emit (events.js:193:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```
Is it a network error?

**Comment by kornelski** [comment]
Yes, that's how Node.JS reports DNS lookup issues.

**Comment by wallpaper-dinding** [comment]
![images (14)](https://user-images.githubusercontent.com/64975171/81561292-2d84c780-93bd-11ea-9f0a-c046ae23fe63.jpg)
