### ISSUE TITLE
Centos8 mozjpeg pre-build test failed

### ISSUE THREAD

**Issue by fly7632785** [mozilla/mozjpeg#413]
Hello everyone, I got an excetion when exec npm install  in Jenkins Platform.

ENV:
```
OS: centos8
node : 14.16.0
image-webpack-loader : 8.1.0
mozjpeg : 7.1.1
```
ERROR:
```
> yorkie@2.0.0 install /var/jenkins_home/workspace/测试环境-Jigsaw Puzzles-web/node_modules/yorkie
> node bin/install.js

CI detected, skipping Git hooks installation

> core-js@2.6.12 postinstall /var/jenkins_home/workspace/测试环境-Jigsaw Puzzles-web/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.1 postinstall /var/jenkins_home/workspace/测试环境-Jigsaw Puzzles-web/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> ejs@2.7.4 postinstall /var/jenkins_home/workspace/测试环境-Jigsaw Puzzles-web/node_modules/ejs
> node ./postinstall.js

Thank you for installing [35mEJS[0m: built with the [32mJake[0m JavaScript build tool ([32mhttps://jakejs.com/[0m)

> cwebp-bin@7.0.1 postinstall /var/jenkins_home/workspace/测试环境-Jigsaw Puzzles-web/node_modules/cwebp-bin
> node lib/install.js

cwebp pre-build test passed successfully

> gifsicle@5.3.0 postinstall /var/jenkins_home/workspace/测试环境-Jigsaw Puzzles-web/node_modules/gifsicle
> node lib/install.js

gifsicle pre-build test passed successfully

> mozjpeg@7.1.1 postinstall /var/jenkins_home/workspace/测试环境-Jigsaw Puzzles-web/node_modules/mozjpeg
> node lib/install.js

Command failed: /var/jenkins_home/workspace/测试环境-Jigsaw Puzzles-web/node_modules/mozjpeg/vendor/cjpeg -version
/var/jenkins_home/workspace/测试环境-Jigsaw Puzzles-web/node_modules/mozjpeg/vendor/cjpeg: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /var/jenkins_home/workspace/测试环境-Jigsaw Puzzles-web/node_modules/mozjpeg/vendor/cjpeg)


mozjpeg pre-build test failed
compiling from source
Error: Command failed: /bin/sh -c autoreconf -fiv
/bin/sh: 1: autoreconf: not found


    at /var/jenkins_home/workspace/测试环境-Jigsaw Puzzles-web/node_modules/bin-build/node_modules/execa/index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
> optipng-bin@7.0.1 postinstall /var/jenkins_home/workspace/测试环境-Jigsaw Puzzles-web/node_modules/optipng-bin
> node lib/install.js

optipng pre-build test passed successfully

> pngquant-bin@6.0.1 postinstall /var/jenkins_home/workspace/测试环境-Jigsaw Puzzles-web/node_modules/pngquant-bin
> node lib/install.js

pngquant pre-build test passed successfully

> highlight.js@9.18.5 postinstall /var/jenkins_home/workspace/测试环境-Jigsaw Puzzles-web/node_modules/highlight.js
> node deprecated.js

[41m[37m-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*[0m
[1m[37m
  Verion 9 of Highlight.js has reached EOL.  It will no longer
  be supported or receive security updates in the future.
  Please upgrade to version 10 or encourage your indirect
  dependencies to do so.

  For more info:
  [34m
  https://github.com/highlightjs/highlight.js/issues/2877
  https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_UPGRADE.md
 [41m[37m
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*[0m
npm notice created a lockfile as package-lock.json. You should commit this file.
```

`ZLIB_1.2.9' not found   and  autoreconf: not found are the keywords.
 I've tried   'yum  -y install autoconf automake libtool', but it doesn't work.

Please help me, thank you

**Comment by kornelski** [comment]
This project is for a C library, and does not support Node.js. Please report it to authors of Node packages you use.
